site_name: CodeMeta Governance
docs_dir: Chapters
theme: readthedocs
use_directory_urls: true
nav:
- 'Governance': governance/
- 'People': people/

copyright: Copyright &copy; 2022-2023 - CodeMeta Contributors.

markdown_extensions:
- codehilite:
   guess_lang: false
